language: julia

os:
  - osx
  - linux

julia:
  - 0.5

notifications:
  email: false

before_install:
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
   - julia  --check-bounds=yes -e 'Pkg.clone("https://github.com/JuliaInv/jInv.jl"); Pkg.build("jInv");'

script:
    - julia  --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("JOcTree");  Pkg.test("JOcTree";coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("JOcTree")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

